### ISSUE TITLE
[bug] missing client/v0.32.0 tag

### ISSUE THREAD

**Issue by vbehar** [siderolabs/omni#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to upgrade our omni integration to v0.32.0, but I couldn't use the "v0.32.0" version for the "client" module, because the `client/v0.32.0` tag is missing.

output of the "go mod tidy" command:
```
github.com/siderolabs/omni/client@v0.32.0: reading github.com/siderolabs/omni/client/go.mod at revision client/v0.32.0: unknown revision client/v0.32.0
```

### Expected Behavior

go mod tidy doesn't complains

### Steps To Reproduce

1. update the omni/client version in go.mod
2. run "go mod tidy"

### Anything else?

there are already existing tags for:
- client/v0.31.1
- client/v0.31.0

**Comment by frezbo** [comment]
Thanks for reporting, fixed https://github.com/siderolabs/omni/tree/client/v0.32.0

**Comment by vbehar** [comment]
that was fast! thanks!

**Comment by vbehar** [comment]
interesting, I still have an error, but a different one:

```
github.com/siderolabs/omni/client@v0.32.0: verifying module: github.com/siderolabs/omni/client@v0.32.0: reading https://sum.golang.org/lookup/github.com/siderolabs/omni/client@v0.32.0: 404 Not Found
	server response: not found: github.com/siderolabs/omni/client@v0.32.0: invalid version: unknown revision client/v0.32.0
```

although if I try with `GONOSUMDB="github.com/siderolabs/omni*"` it works properly, I think there's some cache at the sum.golang.org level that will need to be refreshed, I'm not sure if it will happen automatically at some point or not...

see https://pkg.go.dev/github.com/siderolabs/omni/client?tab=versions vs https://pkg.go.dev/github.com/siderolabs/omni?tab=versions

**Comment by frezbo** [comment]
@smira did i miss something while tagging?

**Comment by smira** [comment]
it looks correct, I wonder if it will take some time for the changes to propagate, not sure at the moment

**Comment by frezbo** [comment]
Something is weird, I get:

```text
❯ go mod tidy
go: finding module for package github.com/siderolabs/omni/client
go: foo imports
        github.com/siderolabs/omni/client: module github.com/siderolabs/omni/client@latest found (v0.32.0), but does not contain package github.com/siderolabs/omni/client
```

**Comment by vbehar** [comment]
yes it works now, I think it took a bit of time for the golang sum database to update its cache.
