### ISSUE TITLE
[bug] Boot loop when using older ISO version on newer Talos cluster.

### ISSUE THREAD

**Issue by jahanson** [siderolabs/omni#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Due to  siderolabs/omni-feedback#79 I had to use an older version to get extension support on my download media. I had to mount this media as an ISO. Once it started talking to the cluster it realized it was out of date (v1.6.4 instead of v1.6.5). So it started the upgrade procedure and rebooted. It's now booting from the ISO again and v1.6.4.

1. Boot from ISO
2. Cluster Communication
3. Upgrade Procedure
4. Reboot and repeat (bootloop)

### Expected Behavior

1. Boot from ISO
2. Cluster Communication
3. Realize it's an ISO somehow and don't upgrade/reboot?

### Steps To Reproduce

1. Shut an active node down, letting it cordon and drain. 
2. put new media in to swap the incorrect Extensions
3. Let it boot and it will bootloop since it's not the actual hard drive.

**Comment by Unix4ever** [comment]
FIxed as part of https://github.com/siderolabs/omni/issues/43
