### ISSUE TITLE
[bug] UI bogs down with lots of nodes

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/omni#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we add lots of nodes to a cluster, Cluster Overview causes Omni to become totally unresponsive.

### Expected Behavior

Cluster Overview shows a subset of cluster resources, allowing us not to get bogged down.

### Steps To Reproduce

Add a bunch of nodes

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by smira** [comment]
Proposed: hide the resource usage diagram for "big" clusters.

**Comment by Unix4ever** [comment]
I wonder if it makes sense to introduce an additional `ClusterMetrics` resource that reports size of a cluster.
I'm afraid otherwise the UI won't be able to tell that it shouldn't load cluster stats for a cluster without fetching all machines for it.

**Comment by smira** [comment]
We already have a `ClusterStatus` which has number of machines?
