### ISSUE TITLE
[bug] Pushing of machine logs seems expensive

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/omni#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For customers with lots of nodes, in monitoring we see the 10m timer where we push machine logs to the ceph volumes seems to heavily saturate the I/O.

### Expected Behavior

This is maybe an exploration of how we might make this less heavy (if we even determine it's something we should be worried about).

### Steps To Reproduce

N/A

### Anything else?

![Screenshot from 2024-04-08 11-05-59](https://github.com/siderolabs/omni/assets/1529818/e85ce8c5-9b04-4ac2-b9c7-9ca6ee63bc14)

^ An example, but I've seen quite a bit higher percentage than this. Saw over 300% last week.

**Comment by smira** [comment]
Ideas:

* compress logs (less I/O)
* push less aggressively
* don't push if no new logs came in the last period
