### ISSUE TITLE
Adding new nodes to omni is resulting in broken installer pulls / 400 requests against image factory?

### ISSUE THREAD

**Issue by Brennan-VanderLaan** [siderolabs/omni#122]
Slack link to other person posting about this: https://taloscommunity.slack.com/archives/C04D4PDAJT0/p1712589217872239

When creating new clusters in omni and using omni install media you get 400 errors on node install:

[talos] task install (1/1): starting
08/04/2024 17:08:50
[talos] pulling "factory.talos.dev/installer/85d01a4ed9d64b5a312ae3326db6ad8c4b8fbc15f467452d674959b6f0683fec:v1.6.7"
08/04/2024 17:08:50
[talos] retrying error: failed to pull image "factory.talos.dev/installer/85d01a4ed9d64b5a312ae3326db6ad8c4b8fbc15f467452d674959b6f0683fec:v1.6.7": failed to resolve reference "factory.talos.dev/installer/85d01a4ed9d64b5a312ae3326db6ad8c4b8fbc15f467452d674959b6f0683fec:v1.6.7": unexpected status from HEAD request to https://factory.talos.dev/v2/installer/85d01a4ed9d64b5a312ae3326db6ad8c4b8fbc15f467452d674959b6f0683fec/manifests/v1.6.7: 400 Bad Request
08/04/2024 17:09:00
[talos] kubernetes endpoint watch error {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "failed to list *v1.Endpoints: Get \"https://[fdae:41e4:649b:9303::1]:10000/api/v1/namespaces/default/endpoints?fieldSelector=metadata.name%3Dkubernetes&limit=500&resourceVersion=0\": EOF - error from a previous attempt: read tcp [fdae:41e4:649b:9303:5ced:12b6:2285:8272]:42060->[fdae:41e4:649b:9303::1]:10000: read: connection reset by peer"}
08/04/2024 17:09:11

If you try to pull the image:

docker pull factory.talos.dev/installer/85d01a4ed9d64b5a312ae3326db6ad8c4b8fbc15f467452d674959b6f0683fec:v1.6.7
Error response from daemon: error parsing HTTP 400 response body: invalid character 'e' looking for beginning of value: "error enhancing profile from schematic: official extension \"siderolabs/modules.dep\" is not available for Talos version v1.6.7\n"

**Comment by smira** [comment]
This seems to be the issue with Omni mis-calculating the schematic (`modules.dep`).

**Comment by bernardgut** [comment]
Same issue here. With default configs on Omni/Talos 1.6.7 running in Proxmox

**Comment by krobertson** [comment]
Does this require upgrading on-premise omni installs or re-generating any install media?

I use hosted and on-prem omni, and have existing install media for both on USB and PXE. Will I need to regenerate those for my existing clusters?

**Comment by utkuozdemir** [comment]
> Does this require upgrading on-premise omni installs or re-generating any install media?
> 
> I use hosted and on-prem omni, and have existing install media for both on USB and PXE. Will I need to regenerate those for my existing clusters?

No, they will keep working fine. All downloaded media are valid, as if they were not, they would fail to download/be pulled in the first place.

The invalid schematic ID was caused by a bug in Omni where it mis-computed the schematic ID of a Talos machine connected to it. The fix should be enough to get things working again.

It is included in the release 0.32.2, and is being rolled out right now.
