### ISSUE TITLE
[bug] cluster status timeout

### ISSUE THREAD

**Issue by brantgurga** [siderolabs/omni#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With backing machines off, cluster status got the status but then it took its sweet time before saying "Error: context deadline exceeded"

### Expected Behavior

I would have expected a shorter timeout period before the command completed.

### Steps To Reproduce

Run command like: `.\omnictl-windows-amd64.exe --omniconfig .\omniconfig.yaml cluster status test-cluster`

### Anything else?

Output was:
```
Could not authenticate: key expired
Attempting to open URL: https://wheatonvanlines.omni.siderolabs.io/omni/authenticate?flow=cli&public-key-id=99a539d3d6b0945b71298290e1013b08fb1e2640
Public key 99a539d3d6b0945b71298290e1013b08fb1e2640 is now registered for user brant_gurganus@wvlcorp.com
PGP key saved to C:\Users\brant_gurganus\AppData\Local\omni\keys\default-brant_gurganus@wvlcorp.com.pgp
Cluster "test-cluster" RUNNING Not Ready (0/3) (healthy/total)
├── Kubernetes Upgrade Done
├── Talos Upgrade Done
├── Control Plane "test-cluster-control-planes" Running Not Ready (0/1)
│   ├── Load Balancer Not Ready
│   ├── Status Checks Failing: [WireguardConnection]
│   └── Machine "44e430bc-382b-4cb0-8ec8-2f7737633e48" SHUTTING_DOWN Unreachable
└── Workers "test-cluster-workers" Running Not Ready (0/2)
    ├── Machine "96bbdc00-5496-4d0e-8396-9f38bd103e1e" SHUTTING_DOWN Unreachable
    └── Machine "f502f276-16bd-42e5-b4ef-8165c8006533" SHUTTING_DOWN Unreachable
Error: context deadline exceeded
```

The unexpected delay was before the `Error: context deadline exceeded` line.

**Comment by smira** [comment]
Please see `--wait` flag to the command.
