### ISSUE TITLE
Support Omni join config via machine config

### ISSUE THREAD

**Issue by smira** [siderolabs/omni#13]
Talos since 1.5.0 support partial machine config submitted as user-data, which includes machine configuration for SideroLink join and event sink.

When Talos runs on the cloud platform with user-data support, we can use that to use "vanilla" image of Talos with join config submitted via user-data.

The flow goes like that:

1. Vanilla Talos boots on the cloud.
2. Talos discovers join config as partial machine config in the cloud user-data.
3. Talos joins Omni.
4. Omni pushes full machine config to the machine, which **should** include join configuration.
5. Omni resets the STATE partition, wiping the full machine config.
6. Talos reboots, and re-loads the join config from userdata, cycle repeats.

* [SideroLinkConfig](https://www.talos.dev/v1.6/reference/configuration/siderolink/siderolinkconfig/)
* [EventSinkConfig](https://www.talos.dev/v1.6/reference/configuration/runtime/eventsinkconfig/)
* [KmsgLogConfig](https://www.talos.dev/v1.6/reference/configuration/runtime/kmsglogconfig/)

First goal: make Omni respect join config, that is submit it to the machine with the other bits of the machine config (see also siderolabs/omni-archive#1459). 

> Note: in maintenance mode, there's no way to get machine configuration from Talos, so Omni should synthesize and submit join config as one of the "config patches" if it discovers a machine joined to Omni e.g. without proper kernel args.

Second goal: make Omni publish expected join config in the UI/as a resource.

**Comment by utkuozdemir** [comment]
Testing the full cycle requires a release with this fix: https://github.com/siderolabs/talos/commit/1bb6027ccd7c63ae3a012eb310d1e05027ec1f80

Currently, with a partial machine config, the initial install works, but when the machine is reset and tried to be re-added to a new cluster, the triggered maintenance upgrade causes Talos to crash due to the partial config it holds.

**Comment by smira** [comment]
The fix was merged, so it should be unblocked?

**Comment by utkuozdemir** [comment]
> The fix was merged, so it should be unblocked?

Yep, I'm back at this, but now the way I'm doing, the integration test I'm adding won't even require the fix.
