### ISSUE TITLE
[feature] Add Version Number to Home page for Omni On-Prem

### ISSUE THREAD

**Issue by kenlasko** [siderolabs/omni#131]
### Problem Description

For on-prem deployments, the Omni home page shows the currently assigned image tag as the ```Backend Version```.  If you are running with the "latest" image tag, the version simply shows as "latest"

For those of us who don't mind living on the bleeding edge, it would be nice to see the actual version number in use. 

### Solution

Instead of using the image tag for ```Backend Version```, show the actual backend version currently in use.

### Alternative Solutions

I've considered NOT using the "latest" image tag, but I like to live dangerously.

**Comment by TimJones** [comment]
The versioning happens in the reverse, Omni's internal version is always `latest` until a real release is cut, at which point it builds with a specific release version set internally (which gets displayed on the Omni homepage), and an image is pushed tagged with that same version.

If you just use the `latest` tag for the omni image, it *has* no version to display as it's a development image and essentially unreleased.

**Comment by smira** [comment]
Well, I think it's a bug @TimJones, in fact more of a bug in Kres - we should split the tag vs. the version. The tag is `:latest`, but version is still defined.

**Comment by TimJones** [comment]
Thanks for the clarification @smira. To be clear, with this change the internal version for Omni will be the short commit SHA when using the `latest` image tag?

**Comment by smira** [comment]
> Thanks for the clarification @smira. To be clear, with this change the internal version for Omni will be the short commit SHA when using the `latest` image tag?

it depends to what `:latest` maps right now. if it matches a release, it will be just a release tag, if it's somewhere in between tags, it will be more like `<tag>-<N>-<short SHA>`

I think we also push `:latest` from release and main branches, so it's more of a mess than I thought

**Comment by Unix4ever** [comment]
I guess it's ok to close this now.
