### ISSUE TITLE
[bug] Machine User Labels are not added to the VMWare (amd64) Installation Media (OVA). 

### ISSUE THREAD

**Issue by RvRuttenFS** [siderolabs/omni#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the Download Installation Media screen a user can add Machine User Labels. Hen using the VMWare (amd64) Installation Media (OVA) these Machine User Labels are not shown when the machine registers to Omni. The use case is to match on this label in the Machine Class. Tested it also with the ISO, but that works fine.

### Expected Behavior

Machine User Labels is used when the machine registers to Omni.

### Steps To Reproduce

1. Click on Download Installation Media in Omni
2. Select the VMWare (amd64) option.
3. Add a Machine User Labels. e.g. role:controlplane
4. Boot a machine using the OVA file.
5. Check in the Machines menu.
6. User defined label is not showing up.

### What browsers are you seeing the problem on?

Chrome

**Comment by rsmitty** [comment]
I was able to make this work in my own testing in this environment, just fyi. Make sure that, after adding the label, you hit "enter" to make it apply. It should light up when actually applied. Not doing this won't error (that's a bad UX and we should fix).

Should look like this before hitting submit:
![image](https://github.com/siderolabs/omni/assets/1529818/ff1d01b4-e2d9-43dc-815d-1b49d30870a5)

**Comment by rsmitty** [comment]
I _think_ this is just #136, but please check again and let me know if that's not correct.

**Comment by RvRuttenFS** [comment]
Yes, this is fixed. Closing.
