### ISSUE TITLE
[bug] Extensions not loading properly due to wrong image being loaded

### ISSUE THREAD

**Issue by bernardgut** [siderolabs/omni#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On Omni:latest image, Talos 1.6.7:

-  In the GUI, Create an ISO boot medium `iso-1`, add `ZFS` as extension 
-  Boot `iso-1`, create a cluster in Omni GUI, add your machine config loading your extension, wait for the cluster to come up, check the extensions loaded with `talosctl`, delete the cluster, 
-  Create a new ISO boot medium `iso-2`, add `DRBD` as extension 
-  Wipe the node with `iso-2`, create a new cluster in the Omni GUI, add the node, add the new config loading your extensions, wait for the cluster to come up, check the extensions loaded with `talosctl`.
- The loaded extensions are the same as in `iso-1` (zfs). The extension of `iso-2` are missing (drbd). And you will see errors such as `talos] controller failed {"component": "controller-runtime", "controller": "runtime.KernelModuleSpecController", "error": "error loading module \"drbd\": module not found"}` when applying your config patches.

### Expected Behavior

- The loaded extensions should be the ones added to the new ISO when the node is provisioned with the new ISO.

The only way I found to fix this is to completely remove the node from omni then wipe the node, then mount the new image, then start over by adding back the node to omni, patch configs, etc.

### Steps To Reproduce

See Current Behavior

**Comment by Unix4ever** [comment]
If Talos is already installed on the node it won't pick the extensions from the ISO.
The best option here would be to use cluster templates and specify the correct set of extensions you want to use on the node.

```
---
kind: Machine
systemExtensions:
  - siderolabs/drbd...
```

**Comment by bernardgut** [comment]
Yes actually this was fixed in Talos 1.7. I think you can close this.
