### ISSUE TITLE
[ETCD backup for omni] not working for google storage

### ISSUE THREAD

**Issue by marcpar** [siderolabs/omni#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error: failed to create resource 'etcd-backup-s3-conf' 'EtcdBackupS3Configs.omni.sidero.dev': rpc error: code = InvalidArgument desc = failed to validate: 1 error occurred:
        * incorrect settings for s3 client: failed to list objects in bucket "testbucketforetcd": operation error S3: ListObjects, https response error StatusCode: 403, RequestID: , HostID: , api error SignatureDoesNotMatch: Access denied.

### Expected Behavior

omnictl apply successful

### Steps To Reproduce

1. create a etcdbackup omni yaml 
2. apply in omni

### What browsers are you seeing the problem on?

Chrome

**Comment by smira** [comment]
Does your google storage work correctly with e.g. `awscli` using same settings?

**Comment by marcpar** [comment]
> awscli

yes according to google https://stackoverflow.com/questions/47095834/how-to-access-google-cloud-storage-bucket-using-aws-cli

**Comment by smira** [comment]
You mean you verified that it does work with same credentials you used with Omni?

**Comment by marcpar** [comment]
not successful on aws but according to online it works. I might be missing something

**Comment by marcpar** [comment]
got it to work but its failing for etcdbackup 
aws s3 ls s3://testbucketforetcd --endpoint-url https://storage.googleapis.com
2024-04-23 18:32:11        212 argo-css.yaml 


![image](https://github.com/siderolabs/omni/assets/2436074/8ad84cab-3bb4-4518-a799-6c68acda44a3)
