### ISSUE TITLE
[bug] Deleting hundreds of links renders Omni unusable

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/omni#174]
It looks like COSI runtime just hangs after that:
- no way to read the state.
- no controllers work.

**Comment by Unix4ever** [comment]
Actually read works, but not the watch.
And I guess it's the same reason why controllers stop working.

**Comment by smira** [comment]
What we know so far: it hangs in `etcd` client Watch API, 'Get'/'List' requests still work.
