### ISSUE TITLE
[feature] Break glass solution

### ISSUE THREAD

**Issue by ArcherSeven** [siderolabs/omni#191]
### Problem Description

We need a fallback method for connecting to our Talos clusters if Omni is offline.

### Notes

This has been discussed at length previously, but idk if it is being tracked anywhere.  I was unable to find it if so.

**Comment by rothgar** [comment]
Would you want Kubernetes and Talos access in a break glass scenario? Would local console access (with talosctl) be enough?

**Comment by ArcherSeven** [comment]
Because of our edge deployments, we don't have any machines on sites that could be used as a jump box, and only in a few cases do we have VPNs configured to do so, so a fallback proxy for kubectl and talosctl access is really what we're looking for.

**Comment by Unix4ever** [comment]
duplicate to #33
