### ISSUE TITLE
[bug] Dashboard values incorrect

### ISSUE THREAD

**Issue by ArcherSeven** [siderolabs/omni#192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our Dashboards indicate that are resource requests for memory and CPU are substantially higher than they actually are.

### Expected Behavior

Dashboard values correctly reflect those shown from describe node in k8s or similar.

### Steps To Reproduce

Open any cluster, most obviously older clusters, in our production instance.

### What browsers are you seeing the problem on?

Firefox, Chrome

### Anything else?

https://github.com/siderolabs/omni-feedback/issues/56

**Comment by smira** [comment]
I might guess this issue is old, and it got fixed, but it hasn't been closed.

**Comment by Unix4ever** [comment]
I think there might still be something missing in the way we calculate the usage. I've looked into that long time ago, but couldn't find the real issue there, as it's only triggered by some combination of init pods requests or limits.
