### ISSUE TITLE
[feature] Pre-cached images

### ISSUE THREAD

**Issue by ArcherSeven** [siderolabs/omni#193]
### Problem Description

We need a way to load a Talos image that has all of our custom and third party container images pre-loaded onto our machines before shipping to site so that we can assign those machines to clusters on site with as little bandwidth usage as possible.

### Solution

Imagefactory, when run within our cloud, could generate an instance-specific talos image that contains a container image cache containing our needed images.

### Alternative Solutions

A separate utility could write the cache to disk after the talos image has already been written.  But this would probably be both harder to handle and more work to implement.

### Notes

Attempting to track here a request that has been widely discussed previously.

**Comment by rsmitty** [comment]
This will be implemented as https://github.com/siderolabs/talos/issues/9610. Will close this issue in favor of that one.
