### ISSUE TITLE
[bug] Omni not updating existing Kubernetes 1.29.4 to 1.30.0

### ISSUE THREAD

**Issue by xerxist** [siderolabs/omni#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Omni is not showing Kubernetes version 1.30.0 from the list to update from 1.29.4

### Expected Behavior

Version 1.30.0 available from the list to update to.

### Steps To Reproduce

Running a cluster with Kubernetes version 1.29.4 and try to upgrade to 1.30.0

### Anything else?

....

**Comment by smira** [comment]
Make sure your cluster is running Talos 1.7.x, as it's the first version of Talos to support Kubernetes 1.30.

See [Support Matrix](https://www.talos.dev/v1.7/introduction/support-matrix/) for more information.

**Comment by xerxist** [comment]
Yes Talos is definitely on 1.7.0

If I create a new cluster I can select 1.30.0 right away.

**Comment by yoyellow** [comment]
issue persists on latest omni 0.34 release with talos 1.7.1

**Comment by Unix4ever** [comment]
Yep, confirmed. We just need to bump `siderolabs/go-kubernetes` lib there.
Will be fixed in the next release
