### ISSUE TITLE
[bug] missing client/v0.33+ tags

### ISSUE THREAD

**Issue by vbehar** [siderolabs/omni#243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

we don't have the client tags since v0.33.1: https://github.com/siderolabs/omni/tags

### Expected Behavior

each omni release should have 2 tags: vX.Y.Z + client/vX.Y.Z
https://pkg.go.dev/github.com/siderolabs/omni/client?tab=versions should list all available omni releases

### Steps To Reproduce

try to use the client module > v0.33.1

### Anything else?

it was fixed once in https://github.com/siderolabs/omni/issues/104 but somehow the issue came back...

**Comment by Unix4ever** [comment]
Good catch. I still keep forgetting to do that while cutting releases.

**Comment by Unix4ever** [comment]
All tags should be populated now. Thanks for the report.

**Comment by vbehar** [comment]
thanks!
