### ISSUE TITLE
Add wasmedge and spin to install Download Media Pre-Install Extensions list

### ISSUE THREAD

**Issue by ricable** [siderolabs/omni#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

wasmedge and spin exist in https://github.com/siderolabs/extensions/tree/main/container-runtime but do not appear in omni Download Media Pre-Install Extensions list

### Expected Behavior

Would be great to be able to download image with webassembly container-runtime pre installed

### Steps To Reproduce

-

**Comment by smira** [comment]
Please make sure you're using the latest version of Talos, as `spin` was added only in Talos 1.7

**Comment by codespearhead** [comment]
Since it's been a month, should this issue be closed as invalid?

**Comment by Unix4ever** [comment]
Yep, doesn't seem to be valid.
