### ISSUE TITLE
[bug] machine class pages won't load, network errors in chrome console

### ISSUE THREAD

**Issue by garymm** [siderolabs/omni#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Loading a machine class page spins forever.
I see errors in the chrome console.
![Captura de pantalla 2024-05-15 a la(s) 14 13 33](https://github.com/siderolabs/omni/assets/421339/9b52bc3b-6d25-49e8-9ff2-0a2c3c2e539f)

### Expected Behavior

Machine class page loads

### Steps To Reproduce

1. Create a machine class
2. Go back to something else
3. Open the machine class e.g. https://astera.omni.siderolabs.io/omni/machine-classes/staging-gpu-workers

### What browsers are you seeing the problem on?

Chrome

**Comment by Unix4ever** [comment]
This is fixed in v0.36. Duplicate to #249
