### ISSUE TITLE
[feature] Provide quick filter checkboxes for filters for "available" and "connected" on Machines page

### ISSUE THREAD

**Issue by rothgar** [siderolabs/omni#271]
### Problem Description

When you have a lot of machines connected to an omni instance and they are in various states of being used by existing clusters or off/retired it makes it difficult to find the machines you're working with. The search bar is good for complex filtering but IMO the default view of machines should only be machines that are
1. Currently connected
2. Not already provisioned in a cluster (aka available)

### Solution

Create two check boxes near the search bar (checked by default) to toggle machines that are disconnected and unavailable. When the buttons are checked this could fill in the search bar with the correct search terms (to give hints to users how it works), but that's not required and may complicate searches if a user has something in the search bar (eg `gpu=true`) and wants to toggle available machines.

### Alternative Solutions

Right now users can click on the labels they want to show up in the filter bar which is a decent solution but I'm suggesting we hide unusable machines by default and we need a way to show users something is being hidden from them.

### Notes

It would be good if connected and available columns were part of the default output for `omnictl get machines` too

**Comment by Unix4ever** [comment]
I hope labels completion will help with that.

**Comment by rothgar** [comment]
What do you think about disabling unavailable and disconnected machines by default?

**Comment by Unix4ever** [comment]
If you're talking about cluster creation page it is already always filtered there.
But on the machines page we should always show all machines.

**Comment by rothgar** [comment]
Is there a limit to when we wouldn't want to show all machines? IMO once you have a dozen or so machines it would make sense to hide machines already being used by default.

**Comment by Unix4ever** [comment]
I don't think there should be a limit on the `Machines` page. It's intended to show all machines: available, unavailable, disconnected.

On the cluster creation or scaling pages we already hide all machines which are not available.
