### ISSUE TITLE
embedded_etcd","local-member-id":"8e9e05c52164694d","timeout":7}

### ISSUE THREAD

**Issue by pkleingu** [siderolabs/omni#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

{"level":"info","ts":1716658479.8065062,"caller":"qruntime/qruntime.go:284","msg":"reconcile succeeded","component":"omni_runtime","controller":"TalosExtensionsController","namespace":"default","type":"TalosVersions.omni.sidero.dev","id":"1.7.1","job":"reconcile","busy":0.189914864}
{"level":"info","ts":1716658479.9956317,"caller":"qruntime/qruntime.go:284","msg":"reconcile succeeded","component":"omni_runtime","controller":"TalosExtensionsController","namespace":"default","type":"TalosVersions.omni.sidero.dev","id":"1.7.2","job":"reconcile","busy":0.189064213}
{"level":"info","ts":1716658518.7817183,"caller":"etcdserver/corrupt.go:276","msg":"starting compact hash check","component":"server","component":"embedded_etcd","local-member-id":"8e9e05c52164694d","timeout":7}
{"level":"info","ts":1716658518.7817569,"caller":"etcdserver/corrupt.go:335","msg":"finished compaction hash check","component":"server","component":"embedded_etcd","number-of-hashes-checked":0}

### Expected Behavior

go further with installation from omni on ubuntu init clould but is is only repeating 335 and 276  msg.

### Steps To Reproduce

eviroment = ubuntu LTS 2404 and ubuntu Lts 20.04
Docker version 26.1.3

### Anything else?

Docker run \
  --net=host \
  --cap-add=NET_ADMIN \
  -v $PWD/etcd:/_out/etcd \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /dev/net/tun:/dev/net/tun  \
  -v /etc/letsencrypt/live/omni.domain.nl/fullchain.pem:/tls.crt \
  -v /etc/letsencrypt/live/omni.domain.nl/privkey.pem:/tls.key \
  -v $PWD/omni.asc:/omni.asc \
  ghcr.io/siderolabs/omni \
    --account-id=${OMNI_ACCOUNT_UUID} \
    --name=onprem-omni \
    --cert=/tls.crt \
    --key=/tls.key \
    --siderolink-api-cert=/tls.crt \
    --siderolink-api-key=/tls.key \
    --private-key-source=file:///omni.asc \
    --event-sink-port=8091 \
    --bind-addr=0.0.0.0:443 \
    --siderolink-api-bind-addr=0.0.0.0:8090 \
    --k8s-proxy-bind-addr=0.0.0.0:8100 \
    --advertised-api-url=https://Omni.domain.nl/ \
    --siderolink-api-advertised-url=https://Omni.domain.nl:8090/ \
    --siderolink-wireguard-advertised-addr=192.168.10.100:50180 \
    --advertised-kubernetes-proxy-url=https://Omni.domain.nl:8100/ \
    --auth-auth0-enabled=true \
    --auth-auth0-domain=dev-gppjrsw3ykeyeu.auth0.com \
    --auth-auth0-client-id=zR2BqeJrR7FkeyYC5UJyEGSI1P \
    --initial-users=gmailuser@gmail.com

**Comment by pkleingu** [comment]
my fault :)

**Comment by pkleingu** [comment]
bug can be closed, my fault

**Comment by G3rw1nn** [comment]
How did you solve this issue? Thanks!
