### ISSUE TITLE
[bug] Docs link for self hosting Omni on prem does not work

### ISSUE THREAD

**Issue by s04** [siderolabs/omni#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I reach a 404 page at:

https://omni.siderolabs.com/how-to-guides/how-to-deploy-omni-on-prem/

Which is the link in the installation guide in the Omni repo.

### Expected Behavior

I expect to be redirected to an existing page with installation instructions for self-hosting omni.

### Steps To Reproduce

Click the link under the install heading marked "[instructions in the documentation](https://omni.siderolabs.com/docs/how-to-guides/self-hosted/how-to-deploy-omni-on-prem/)"

**Comment by utkuozdemir** [comment]
Fixed in https://github.com/siderolabs/omni/commit/0bd2a420e85901ba2e4d4137823bafc391896020
