### ISSUE TITLE
[bug][v0.36.0-beta.0-16-gccca5b5] Cluster teardown/destroy seems to get stuck with "invalid state"

### ISSUE THREAD

**Issue by samip5** [siderolabs/omni#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had a cluster with Kubernetes 1.30.1 and Talos 1.7.1, and it seems master has been left in "invalid state" and the cluster in Omni is stuck in destroying as a result.

### Expected Behavior

I would have expected it to just work. It did manage to do it for my worker.

### Steps To Reproduce

1. Deploy 1.7.2 Talos with Kubernetes 1.30.1
2. After cluster has been  created, destroy it
3. See that it's stuck

**Comment by Unix4ever** [comment]
Main branch of Omni can have some serious bug, I won't recommend using it.
Which commit is that? I couldn't find this commit hash.

Everything after this commit is currently highly unstable right now:
https://github.com/siderolabs/omni/commit/9bce82ad769d0042993302bf08cebf6abcbe7d2c

The main branch should get back into shape after we merge this PR
https://github.com/siderolabs/omni/pull/300

**Comment by samip5** [comment]
I had not realized that it's master but that would make sense then.

Image SHA256: `sha256:601668979dc3ceec57871160b90d183d0fcbe2d466bd45b49e3a6ed527bb8529`
