### ISSUE TITLE
[bug] Validate user email format

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/omni#312]
### Problem Description

When adding a new user to an existing Omni account, there seems to be no validation of email address entered.
It happily accepted the below invalid email address for a user:
`The User steverfrancis@2@gmail.com is created`
`The User select * from tables is created`

### Solution

There are lots of javascripts to validate emails.

**Comment by Unix4ever** [comment]
> `The User select * from tables is created`

I'm glad we don't use `sql` :D
