### ISSUE TITLE
[feature] Show "pending" reconfiguration for locked machines

### ISSUE THREAD

**Issue by TimJones** [siderolabs/omni#342]
### Problem Description

I applied a config change (via cluster template) to a cluster. After doing so I looked at the UI and saw everything green/ready and assumed the change had been applied correctly, but since my workers were locked the check had only been applied to the control plane.

### Solution

Much like the "Reconfiguring" status, maybe we could show "Pending reconfiguration" or "Reconfiguration needed" on the machine status in the UI.

**Comment by Unix4ever** [comment]
That's duplicate to https://github.com/siderolabs/omni/issues/15

**Comment by TimJones** [comment]
Thanks! Sorry I didn't find it when opening this ticket :disappointed:
