### ISSUE TITLE
[feature] Cleaner design for Clusters page

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/omni#387]
### Problem Description

On the clusters page, it is not immediately intuitive what is a cluster versus a machine:
![image](https://github.com/siderolabs/omni/assets/67986293/12830af8-5159-4e96-a0f4-5144e49f7d45)
 

### Solution

Indent hierarchically:
![image](https://github.com/siderolabs/omni/assets/67986293/7df94a0c-b424-45b3-8cb3-cfaec62fcfec)

I find this much clearer.

**Comment by Unix4ever** [comment]
How about this?

<img width="1448" alt="Screenshot 2024-06-19 at 17 55 33" src="https://github.com/siderolabs/omni/assets/830532/cc1f2040-bb92-4c96-a7f2-bc00829756d9">

**Comment by steverfrancis** [comment]
I dont like the inconsistent indentation - the fact that machines are left of the class (work or control plane) means it is not immediately apparent the distinction between a new cluster and a machine.

**Comment by Unix4ever** [comment]
<img width="1443" alt="Screenshot 2024-06-19 at 22 23 43" src="https://github.com/siderolabs/omni/assets/830532/124bec74-c12e-4054-8231-31050b488d33">

**Comment by Unix4ever** [comment]
More options:

<img width="364" alt="Screenshot 2024-06-19 at 22 33 35" src="https://github.com/siderolabs/omni/assets/830532/
<img width="370" alt="Screenshot 2024-06-19 at 22 34 07" src="https://github.com/siderolabs/omni/assets/830532/67825fba-1c5a-4204-a643-9f55b0902cde">
593c22c9-edfd-4cd8-8af5-a5676f01b76a">

**Comment by steverfrancis** [comment]
The second image above (with the indents) looks good.
