### ISSUE TITLE
[bug] Empty, but default, machine set cannot use machine classes

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/omni#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On a new cluster with no workers, there exists a default machine set, called `<cluster-name>-workers`.
You can click "Use machine classes", and select a valid class, but on saving this gives an error that the machine set is using manual management, and cannot be switched to using machine classes.
![image](https://github.com/siderolabs/omni/assets/67986293/d01f54a0-792e-48ec-be04-3b0e40b8ddcd)

### Expected Behavior

I would expect that the machine set, at least when empty and unused, be allowed to switch to using machine sets.
Failing that, I would expect that the option to Use Machine classes would not be present. 

### Steps To Reproduce

Create a cluster with no workers, and try to use machine classes on default machine set.

**Comment by Unix4ever** [comment]
Makes sense for the empty machine sets, thanks!
