### ISSUE TITLE
[feature] Show when "All" members of machine set is selected on cluster overview

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/omni#391]
### Problem Description

From the Cluster overview page, if you change a pool from a specific number (1, in this case):<img width="277" alt="image" src="https://github.com/siderolabs/omni/assets/67986293/8afec38a-0d8e-4199-a838-7d393a135b73">
to using "All":
<img width="362" alt="image" src="https://github.com/siderolabs/omni/assets/67986293/48b8fcab-ce12-4a59-ae66-2f8c33bd29f1">
then click the check box - you cannot tell you changed anything:
<img width="270" alt="image" src="https://github.com/siderolabs/omni/assets/67986293/12073142-f991-485e-9629-a88bd5c70f75">

### Solution

Perhaps append (All) after the second number

**Comment by Unix4ever** [comment]
Can display `1/∞` as an option
