### ISSUE TITLE
[bug] Omni fails to reconnect to external etcd if one member goes down

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/omni#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During yesterday's outage, etcd was consuming all RAM for a given node and essentially killed the node completely. As such, one of three etcd replicas was down. It seems that Omni may be only using one endpoint from the etcd.omni-etcd.svc.cluster.local service, as some subset of the Omnis connected to this cluster went down (but not all of them). They went into 1/2 readiness in Kubernetes and were failing with an error like:

```{"level":"error","ts":1719621171.964277,"caller":"health/health.go:60","msg":"unexpected error on health check","component":"server","error":"etcd call failed on get \"TalosVersions.omni.sidero.dev(default/health-check@undefined)\": context canceled"}```

They never recover unless that replica comes back online and never restart or attempt to reform the connection to another etcd it seems.

### Expected Behavior

Omni reconnects if it fails to talk to the member that has become nonresponsive.

### Steps To Reproduce

Kill a single etcd replica with many Omnis connected. Some subset of them will fail.

**Comment by smira** [comment]
Are we sure that Kubernetes endpoints were correct at that moment? As the client would just use the provided DNS name

**Comment by smira** [comment]
Use K8s headless service.

Enable keepalives client-side (?).
