### ISSUE TITLE
[bug] UI issues with v0.39.0

### ISSUE THREAD

**Issue by devantler** [siderolabs/omni#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/siderolabs/omni/assets/26203420/f701adce-6c6c-4827-8968-866dfe1b821f)

### Expected Behavior

I expect the UI to look as it did prior to the update, where there where no UI glitches.

### Steps To Reproduce

I did nothing. I just noticed the UI bugs this morning, and I saw the version had been bumped. So I guess it is related.

### What browsers are you seeing the problem on?

Safari Version 18.0 (20619.1.18.11.1)

**Comment by pjoomen** [comment]
I experience the same issue with Safari Version 17.5 (19618.2.12.11.6), but not with Chrome Version 126.0.6478.127

**Comment by Unix4ever** [comment]
Thanks for the report, we'll look into it.
