### ISSUE TITLE
[feature] Use Omni as a external kernel log sink

### ISSUE THREAD

**Issue by samip5** [siderolabs/omni#457]
### Problem Description

I may want to create my cluster outside of Omni, but still get machine logs.

### Solution

I want machine logs in Omni even if the cluster is not handled by it otherwise.

### Alternative Solutions

Seperate component that can be used with siderolink for talos event sink AND talos.logging.kernel.

**Comment by smira** [comment]
This is DYI, but the core is available: https://github.com/siderolabs/siderolink

And everything including SideroLink and kernel args is documented, so you can build your own thing if you want to.
