### ISSUE TITLE
[bug] editing a MachineClass in the UI removes the labels

### ISSUE THREAD

**Issue by vbehar** [siderolabs/omni#466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if we try to edit a MachineClass in the omni UI - for example changing the matchLabels - then the MachineClass labels are removed.

### Expected Behavior

omni UI shouldn't remove the MachineClass labels when changing the matchLabels

### Steps To Reproduce

1. Create a MachineClass with labels using the CLI
2. Edit its matchLabels in the UI
3. Retrieve the MachineClass with the CLI in YAML, and notice that the labels are now gone

### What browsers are you seeing the problem on?

Chrome

**Comment by Unix4ever** [comment]
Should be easy to fix, thanks for the report.
