### ISSUE TITLE
[bug] Alignment issues on Safari and Edge (iPad OS)

### ISSUE THREAD

**Issue by rothgar** [siderolabs/omni#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Many of the text and buttons don't align on Safari and Edge on an iPad. They used to be fine but I just opened it recently and a lot of the text is overlapped, hidden, or misaligned.
![IMG_0361](https://github.com/user-attachments/assets/8fc3e09a-7a89-4cf5-ba5b-816d4c6ac9e3)
![IMG_0362](https://github.com/user-attachments/assets/25514d4c-3b6e-4506-ab39-29dd401c5f88)
![IMG_0363](https://github.com/user-attachments/assets/4d21ff59-7089-4e96-86cf-72489709807d)
![IMG_0365](https://github.com/user-attachments/assets/dd9aa175-84e7-4c36-bd97-8fda51800503)

### Expected Behavior

Text and buttons should adapt to smaller screen sizes.

### Steps To Reproduce

1. Open omni on an iPad

### What browsers are you seeing the problem on?

Safari, Microsoft Edge

### Anything else?

I'm running iPad OS 18 public beta. This may be related to the beta but I don't have another iPad to check iPad OS 17.

**Comment by Unix4ever** [comment]
Yeah, that's duplicate to https://github.com/siderolabs/omni/issues/450
