### ISSUE TITLE
[bug] service exposer doesn't work under arm

### ISSUE THREAD

**Issue by lucsoft** [siderolabs/omni#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently just CrashLoopBackOffs with exec /kube-service-exposer: exec format error

### Expected Behavior

A) Make it work under arm or B) Don't allow it under arm

### Steps To Reproduce

1. Create a ARM Cluster
2. Create a Hello World App
3. Tag the Service Correctly
4. Check the Box

### What browsers are you seeing the problem on?

Chrome

**Comment by Unix4ever** [comment]
Thanks for the report.
We'll update kube-service-exposer service in Omni 0.40.

As of the immediate fix you can manually edit the daemonset: `kubectl edit daemonset omni-kube-service-exposer` and change the image version to 0.1.4.
Bootstrap manifests will show a diff until we roll out the new Omni version to your account.

**Comment by lucsoft** [comment]
Great! Thanks for the fast fix, works as intended :)
