### ISSUE TITLE
[bug] `siderolink-wireguard-advertised-addr` accepts both IPv4 and IPv6 addresses, but Talos fails to parse the result

### ISSUE THREAD

**Issue by samip5** [siderolabs/omni#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently the argument will accept both address families but then fail to parse it on Talos

### Expected Behavior

I expected it to be able to connect via either IPv6 address or IPv4, but instead talos says too many colons in address.

### Steps To Reproduce

1. Deploy Omni somewhere where it has dual-stack support
2. Specify via `siderolink-wireguard-advertised-addr` both address families like `--siderolink-wireguard-advertised-addr=[2a01:<snip>:<snip>:559::1]:50180,65.<snip>.<snip>.136:50180`
3. Download install media and boot up machines with it

### Anything else?

I wasn't sure if this issue should be created here or in Talos repo.

**Comment by DmitriyMV** [comment]
It looks like wireguard library [doesn't support](https://github.com/siderolabs/wgctrl-go/blob/master/internal/wglinux/configure_linux.go#L148) specifying several endpoints for the single peer, so the only thing we can do is prohibit specifying two and more IP's in `siderolink-wireguard-advertised-addr`.

**Comment by DmitriyMV** [comment]
Yes, if we go with user mode endpoint rotation we can do it. There will be some delay if first endpoint is unavailable and same applies during endpoints rotation.
