### ISSUE TITLE
[bug] Omni doesn't reload certs

### ISSUE THREAD

**Issue by rsmitty** [siderolabs/omni#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running a self hosted Omni, we're using certbot to handle certificate generation and renewal. Omni then uses these certs. However, even though certbot renews the certs as expected, Omni doesn't reload the certs upon this renewal. Leads to an error in browser and kube proxy not functioning at all.

### Expected Behavior

Omni sees cert changes and reloads as necessary.

### Steps To Reproduce

1. Gen certs with certbot
2. Use these certs with a basic docker run for the omni container
3. Wait for cert renewal
4. Omni shows expired cert errors.

**Comment by smira** [comment]
The easiest solution is to copy from `etcd` - they load the certs each time `tls.Config` is used.
