### ISSUE TITLE
[bug] Updated Talos 1.7.5 to 1.7.6 via Omni cluster template sync and process seems to have stalled

### ISSUE THREAD

**Issue by brantgurga** [siderolabs/omni#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cluster has 1 control plane and 2 worker nodes. Control plane appears to have updated and reports Ready. First worker node seems stuck. Console logs from that node as displayed in Omni indicate a missing key file, but Andrey Smirnov on Slack thought that was unrelated.

Last logs from problematic node as reported in Omni:
```
06/08/2024 09:50:47
XFS (sda3): Unmounting Filesystem 38b11088-49f6-4dd6-97d1-39554d8f8bb3
06/08/2024 09:50:47
[talos] task kexecPrepare (1/1): done, 1.149714927s
06/08/2024 09:50:47
[talos] phase kexec (12/14): done, 1.15005722s
06/08/2024 09:50:47
[talos] phase stopEverything (13/14): 1 tasks(s)
06/08/2024 09:50:47
[talos] task stopAllServices (1/1): starting
06/08/2024 09:50:47
[talos] service[apid](Stopping): Sending SIGTERM to task apid (PID 2003, container apid)
06/08/2024 09:50:47
[talos] service[dashboard](Stopping): Sending SIGTERM to Process(["/sbin/dashboard"])
06/08/2024 09:50:47
[talos] service[syslogd](Finished): Service finished successfully
06/08/2024 09:50:47
[talos] service[dashboard](Finished): Service finished successfully
06/08/2024 09:51:25
[talos] controller failed {"component": "controller-runtime", "controller": "v1alpha1.EventsSinkController", "error": "error publishing event: rpc error: code = Unavailable desc = error reading from server: read tcp [fdae:41e4:649b:9303:50ec:fccd:c176:2bb8]:55446->[fdae:41e4:649b:9303::1]:8090: read: connection reset by peer"}
06/08/2024 09:54:14
[talos] controller failed {"component": "controller-runtime", "controller": "v1alpha1.EventsSinkController", "error": "error publishing event: rpc error: code = Unavailable desc = error reading from server: read tcp [fdae:41e4:649b:9303:50ec:fccd:c176:2bb8]:59894->[fdae:41e4:649b:9303::1]:8090: read: connection reset by peer"}
06/08/2024 09:54:32
[talos] controller failed {"component": "controller-runtime", "controller": "k8s.EndpointController", "error": "error getting endpoints: Get \"https://127.0.0.1:7445/api/v1/namespaces/default/endpoints/kubernetes?timeout=30s\": open /var/lib/kubelet/pki/kubelet-client-current.pem: no such file or directory"}
```

### Expected Behavior

Nodes successfully update to 1.7.6 as desired without any manual interventions or recovery.

### Steps To Reproduce

Unknown if reproducible but starting from a 1.7.5 cluster without anything reporting issues:
1. Update 1.7.5 to 1.7.6 for Talos version on cluster template.
2. Sync cluster template.

**Comment by smira** [comment]
There are two options here, and it's not clear what exactly happened.

* the machine got stuck trying to reboot (so it hasn't rebooted actually, and rebooting it manually would fix things_
* the machine rebooted, but for some reason can't connect to Omni (so you don't see new logs)

The only way to figure out what happened is to look at the machine itself.

We don't believe it's related in any way to 1.7.5/1.7.6 of Talos, but if it is, we'd need the logs of new version and why it fails to connect.

In either case, inspecting console logs of Talos is the next step.

**Comment by brantgurga** [comment]
Rebooting worked. Sysadmin didn't note what was on the console though so I doubt we can see if there was some bug or environmental issue at play at this point. So likely nothing further that can be done. Second worker node appeared to update and restart okay.
