### ISSUE TITLE
kubernetes client cache doesn't work

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/omni#526]
At least `KubernetesStatus` controller seem to create a new client for each cluster every time it restarts.
Cache miss chart:
<img width="1686" alt="Screenshot 2024-08-08 at 14 15 31" src="https://github.com/user-attachments/assets/4d07bc8c-3ef3-4fab-b878-4877980f1c3d">

**Comment by smira** [comment]
The LRU size is 32, so it can't cache more than that many clients, and if the controller tries to recreate all of them, it would fail.
