### ISSUE TITLE
Integrate with Talos Diagnostics

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/omni#54]
### Problem Description

Original problem:

> There is the possibility that a nodes' IP address is in the pod and/or service subnet(s). This results in a broken cluster.

Talos implements a set of checks, and results of these checks are populated as resources (see https://github.com/siderolabs/talos/issues/8682). The remaining piece is the glue to show diasnostics in Omni.

(This is a Talos 1.8 feature).

### Solution

Original solution:

> Warn and even refuse to create a cluster if a machine has an IP address in the pod and/or service subnet(s)

**Comment by smira** [comment]
Should be implemented via https://github.com/siderolabs/talos/issues/8682
