### ISSUE TITLE
[feature] Sort clusters alphabetically

### ISSUE THREAD

**Issue by rothgar** [siderolabs/omni#565]
### Problem Description

Clusters on the cluster page should be sorted alphabetically by name by default. I'm not sure how they're sorted right now, by creation date?

### Solution

It might be beneficial to add a way to sort clusters on the header bar but I don't know when that would be beneficial.

If possible we should also put something in the "phase" column for clusters when they're collapsed
![image](https://github.com/user-attachments/assets/f9cc905c-1c26-4940-8574-7eaf928a0309)

Maybe just bubble up the "running" status when all machines are running or if the cluster/machines are upgrading, provisioning, etc.

**Comment by Unix4ever** [comment]
we'll just make it possible to sort by various fields, like it's done for the machines list.
