### ISSUE TITLE
[bug] Unavailable machine stuck while destroying/scale down

### ISSUE THREAD

**Issue by DianaTheCoderess** [siderolabs/omni#583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/4670823b-6982-468b-8fe4-544c7e70c435)
A machine was unavailable (and could not be rebooted because of disk failure). I tried to remove the machine and the machineset from the cluster, and deleted it from the machines list. Now it is stuck as Unknown/Destroying in the cluster, while it is not shown in the machines tab. 
`omnictl cluster status <cluster-name>`
```
Additional Workers "homenet-cluster-wef3e56" Destroying Not Ready (0/1)
    └── Machine "5b3372b3-c478-1851-bea1-d977e8581b81" UNKNOWN Unreachable Config Outdated
```

### Expected Behavior

The unavailable machine is deleted after a timeout or something similar

### Steps To Reproduce

1. Disconnect the machine
2. Delete the machine from the cluster via the omni UI
3. Delete the machineset
4. Delete the machine in the machines tab

**Comment by Unix4ever** [comment]
Can you please run these commands and post the output:

```
omnictl get machinesetnode 5b3372b3-c478-1851-bea1-d977e8581b81 -o yaml
omnictl get link 5b3372b3-c478-1851-bea1-d977e8581b81 -o yaml
omnictl get machine 5b3372b3-c478-1851-bea1-d977e8581b81 -o yaml
omnictl get machinestatus 5b3372b3-c478-1851-bea1-d977e8581b81 -o yaml
```

And can also run `omnictl support --cluster  <cluster-name>` and post the generated zip here.

**Comment by DianaTheCoderess** [comment]
Thx for the quick response and the commands. I've run them with the following results:
```
> omnictl get machinesetnode 5b3372b3-c478-1851-bea1-d977e8581b81 -o yaml
Error: rpc error: code = NotFound desc = resource MachineSetNodes.omni.sidero.dev(default/5b3372b3-c478-1851-bea1-d977e8581b81@undefined) doesn't exist
```
```
> omnictl get link 5b3372b3-c478-1851-bea1-d977e8581b81 -o yaml
metadata:
    namespace: default
    type: Links.omni.sidero.dev
    id: 5b3372b3-c478-1851-bea1-d977e8581b81
    version: 1687
    owner:
    phase: tearingDown
    created: 2024-05-31T12:54:27Z
    updated: 2024-08-24T22:17:34Z
    finalizers:
        - MachineController
spec:
    nodesubnet: <redacted>
    nodepublickey: <redacted>
    lastendpoint: 192.168.28.192:58756
    connected: false
    virtualaddrport: ""
    remoteaddr: 192.168.39.192
```
```
> omnictl get machine 5b3372b3-c478-1851-bea1-d977e8581b81 -o yaml
metadata:
    namespace: default
    type: Machines.omni.sidero.dev
    id: 5b3372b3-c478-1851-bea1-d977e8581b81
    version: 14
    owner: MachineController
    phase: tearingDown
    created: 2024-05-31T12:54:28Z
    updated: 2024-08-24T22:17:34Z
    labels:
        omni.sidero.dev/address: <redacted>
    finalizers:
        - MachineSetStatusController
spec:
    managementaddress: <redacted>
    connected: false
```
```
> omnictl get machinestatus 5b3372b3-c478-1851-bea1-d977e8581b81 -o yaml
Error: rpc error: code = NotFound desc = resource MachineStatuses.omni.sidero.dev(default/5b3372b3-c478-1851-bea1-d977e8581b81@undefined) doesn't exist
```

So it seems there are still resources pending in the tear down phase. 
I'm not sure about posting the support.zip in here, because of privacy concerns. If you're unable to determine the issue without it, I can upload it anyway.

**Comment by Unix4ever** [comment]
> Is it possible that the finalizers are blocking each other here?

I don't think they block each other. As `Machine` has `MachineSetStatusController` finalizer, it means that there should also be a `ClusterMachine` resource for this machine, which deletion is also blocked for some reason.

Normally if the `Machine` is tearing down, the `ClusterMachine` should be removed without any attempts to reset the node.

Is it on-prem or SaaS Omni?

I guess it is required to look into Omni logs to understand more.

> I'm not sure about posting the support.zip in here, because of privacy concerns. 

If you can join our slack you can DM the support.zip to me. It doesn't contain any secrets.

**Comment by DianaTheCoderess** [comment]
Ok, I think I understand.
It's the SaaS version of Omni.

**Comment by Unix4ever** [comment]
Ok, I guess you've found a bug in Omni.
There is a workaround: you can enable workload proxy on the cluster, wait for the machine to be removed and then enable it back.

We'll provide the fix in the next release of Omni.
