### ISSUE TITLE
[bug] Omni instance IP update breaks both clusters and Omni.

### ISSUE THREAD

**Issue by bernardgut** [siderolabs/omni#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Migrated a test omni instance and had to update `siderolink-wireguard-advertised-addr`. Now my test clusters are orphans and cannot be reached/updated. How do I recover ?

How do we avoid this ? the docs state that `siderolink-wireguard-advertised-addr` needs to be an ip. Cant we use a `hostname:50180` instead ?

### Expected Behavior

Allow seamless changes in network config of Omni instance.

### Steps To Reproduce

1. Create an omni VM. 
2. Create a deploy ISO, create a cluster.
3. Migrate the Omni VM
4. Its dead, Jim.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by smira** [comment]
Talos uses `siderolink.api=` kernel argument to reach back to Omni. This argument might be either a hostname or an IP, both work, but the endpoint should work all the time for the Talos clusters to connect to.

You can recover by either making old endpoint work or by updating running Talos machines (e.g. if you have direct access to edit kernel args).

**Comment by bernardgut** [comment]
Maybe if it now supports both hostname and IP the docs should recommend hostname to avoid these kind of issues ? Something like https://github.com/siderolabs/omni-docs/pull/99 ?

**Comment by bernardgut** [comment]
Either way thanks. Problem solved.
