### ISSUE TITLE
[feature] Automatically resolve node part of a cluster

### ISSUE THREAD

**Issue by rothgar** [siderolabs/omni#620]
### Problem Description

When querying nodes in an omni instance it would be nice to be able to globally query it (assuming the name is unique) no matter what cluster it is in.

```
talosctl services -n my_node
```
Should work even if the node is part of a cluster and I don't specify the cluster at the CLI.

Currently I get an error that is unclear why it happens
```
rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing: dial tcp: lookup mini on 192.168.128.10:53: no such host"
```
but if I add `--cluster my_cluster` it works

### Solution

If there is only one machine with a specific name return that machine with `talosctl` commands.

### Alternative Solutions

We could alternatively make the error message more clear that the user needs to specify a `--cluster` for querying nodes.

**Comment by smira** [comment]
> We could alternatively make the error message more clear that the user needs to specify a --cluster for querying nodes.

I think we should do this asap, as it's clearly a very confusing behavior right now.
