### ISSUE TITLE
[bug] Cloud instance not bumped

### ISSUE THREAD

**Issue by devantler** [siderolabs/omni#634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im still on v0.41.0

### Expected Behavior

I should be on v0.42.1

### Steps To Reproduce

Not relevant

**Comment by smira** [comment]
Omni rollout for the SaaS happens on internal schedule, after extensive testing. The new version will be rolled out to the SaaS as soon as we're ready, please be assured, your instance (like all others) will be updated!

**Comment by devantler** [comment]
Ah okay, I got confused as it is 2 ish releases behind the releases here on GH. Thanks for clarifying:-)
