### ISSUE TITLE
[bug] Omni stops returning machine logs after running for some time

### ISSUE THREAD

**Issue by Unix4ever** [siderolabs/omni#656]
Hard to say what might cause this, instance was running for 11 days.
Logs appeared right after the instance was restarted.
It seems like the whole log history was obtained, so the logs are not dropped, it's just the gRPC API doesn't return anything.

Might worth checking the library for any errors related to log reading.

**Comment by smira** [comment]
Look for Talos logs at the moment the logs stopped flowing - if it failed to deliver, it should log that I think

**Comment by smira** [comment]
> It was sending logs all that time as I could see them after restart, so that's why I think the problem is with reading them

ah... so you think it's the problem with the circular buffer, so it had all of the logs, but never returned them?

**Comment by smira** [comment]
Bumping `go-circular` might fix it?

**Comment by smira** [comment]
A hope is that it was a `go-circular` bug.
