### ISSUE TITLE
[feature] Support `VolumeConfig` in config patches

### ISSUE THREAD

**Issue by judahrand** [siderolabs/omni#677]
### Problem Description

When trying to use a `VolumeConfig` patch as documented [here](https://www.talos.dev/v1.8/reference/configuration/block/volumeconfig/) in Omni I get an error

```
The Config is Invalid
"VolumeConfig" "v1alpha1": not registered
```

### Solution

I assume this is just because this new config option hasn't been added to Omni yet?

**Comment by smira** [comment]
[Omni v0.43.0](https://github.com/siderolabs/omni/releases/tag/v0.43.0) has full support for Talos 1.8.0.
