### ISSUE TITLE
experiment: different type of Talos machines in the integration test

### ISSUE THREAD

**Issue by smira** [siderolabs/omni#69]
Try to create at least two set of machine the easiest way possible:

* connecting to Omni using SideroLink kernel args
* connecting to Omni using partial join machine config

And see what happens to the integration tests, etc.

We can expand to test machines with machine labels in META and not, machines booted from a disk image vs. an ISO, and so on.

**Comment by utkuozdemir** [comment]
Partial join machine config depends on this fix to work end-to-end: https://github.com/siderolabs/talos/pull/8410

Better to start working on this after it lands in a release.

**Comment by smira** [comment]
@utkuozdemir should this be closed now?

**Comment by utkuozdemir** [comment]
yep, we have 3 different types of machines now.
