### ISSUE TITLE
[bug] OMNICONFIG should be optional

### ISSUE THREAD

**Issue by nadenf** [siderolabs/omni#749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Following the instructions in the [documentation](https://omni.siderolabs.com/how-to-guides/install-and-configure-omnictl
):

I run the command:
```
omnictl get clusters
```

And receive an error:
```
Could not authenticate: open /Users/naden/Library/Application Support/omni/keys/default-.pgp: no such file or directory
Error: open /Users/naden/Library/Application Support/omni/keys/default-.pgp: no such file or directory
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:8080: connect: connection refused"
```

Until I set the following as the documentation suggests:
```
export OMNICONFIG=~/.config/omni/config
```

### Expected Behavior

OMNICONFIG should default to ~/.config/omni/config if not set.

### Steps To Reproduce

1. Install omnictl 0.44 and ensure OMNICONFIG is not set.
2. Run omnictl get clusters
3. Should show error message as above.

**Comment by Unix4ever** [comment]
The trick is that we use `xdg` library, which works differently on OSX.
So the config is stored on the `/Users/naden/Library/Application\ Support/omni/config` path on the OSX.

**Comment by nadenf** [comment]
@Unix4ever .. I should have worded this bug a bit better. 

I followed the instructions on this [page](https://omni.siderolabs.com/how-to-guides/install-and-configure-omnictl) and was unable to use Omni. Either it should be updated to mention that I need to do an export or you should just default to the xdg path on Mac.
