### ISSUE TITLE
[feature] omnictl kubernetes available version list

### ISSUE THREAD

**Issue by rothgar** [siderolabs/omni#83]
### Problem Description

When trying to upgrade a cluster via omnictl we need to provide a `--to` flag but there's no way of getting a list of available versions.

### Solution

The current command to upgrade a cluster is something like
```
omnictl cluster kubernetes upgrade-pre-checks cube --to v1.25
```
There should be an option to list available versions like
```
omnictl cluster kubernetes list-versions cube
```
This could print an ordered list of what versions a cluster could be upgraded to.

### Alternative Solutions

It would also be nice if there were a `--next` flag or `--next-minor` and `--next-major` so you didn't need to know the exact version but you could still upgrade quickly.

**Comment by smira** [comment]
`omnictl get kubernetesversions` should give you the list of available versions iirc.
