### ISSUE TITLE
hardware

### ISSUE THREAD

**Issue by Jacky949** [siderolabs/omni#94]
### Is there an existing issue for this?

- [X]I would like to ask about the hardware specifications for 6 nodes

### Current Behavior

I would like to ask about the hardware specifications for 6 nodes

### Expected Behavior

I would like to ask about the hardware specifications for 6 nodes

### Steps To Reproduce

I would like to ask about the hardware rules for 6 nodes.

**Comment by smira** [comment]
Please see https://www.talos.dev/v1.6/introduction/system-requirements/.

This doesn't seem like a bug, probably a better place will be GitHub discussions.
