### ISSUE TITLE
[bug] S3 Backups Storage requires AWS Region

### ISSUE THREAD

**Issue by asininemonkey** [siderolabs/omni#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to setup Backups Storage with an S3 bucket in the `eu-west-1` region results in the following error:

```
Failed to Update Storage Config

failed to validate: 1 error occurred: * incorrect settings for s3 client: failed to list objects in bucket "xxx-omni": operation error S3: ListObjects, https response error StatusCode: 400, RequestID: 3ZG3V67A2GX1B334, HostID: AzxzXxND+i+wMTbA7xjQNsa+IgUZi/dJDarmvtLJBuxW/lKod3aNrLnt4ecvA/kqmpCcTOy5dCk=, api error AuthorizationHeaderMalformed: The authorization header is malformed; a non-empty region must be provided in the credential. 
```

There is no form field to allow a region to be specified.

### Expected Behavior

S3 Backups Storage to be enabled with the provided endpoint, bucket name, access key and secret key.

### Steps To Reproduce

![image](https://github.com/siderolabs/omni/assets/65740649/1fca0fc1-d96a-4b26-aa8c-42ffa9a68c48)

Also confirmed via the command line:

```
$ AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxx AWS_REGION= aws s3 --endpoint-url https://s3.dualstack.eu-west-1.amazonaws.com ls s3://xxx-omni

An error occurred (AuthorizationHeaderMalformed) when calling the ListObjectsV2 operation: The authorization header is malformed; a non-empty region must be provided in the credential.

$
```
```
$ AWS_ACCESS_KEY_ID=xxx AWS_SECRET_ACCESS_KEY=xxx AWS_REGION=eu-west-1 aws s3 --endpoint-url https://s3.dualstack.eu-west-1.amazonaws.com ls s3://xxx-omni

$
```

### What browsers are you seeing the problem on?

Firefox

**Comment by Unix4ever** [comment]
Thanks for the report, it'll be shipped in 0.33
